package com.jingxin.hibernate.model;

// Generated 2015-12-30 11:13:07 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Apply generated by hbm2java
 */
@Entity
@Table(name = "apply", catalog = "jingxin")
public class Apply implements java.io.Serializable {

	private Integer id;
	private User user;
	private String name;
	private String sex;
	private Date brithday;
	private String idCard;
	private String politicalStatus;
	private String nation;
	private String workType;
	private String workName;
	private String department;
	private String workAddress;
	private String inchPhoto;
	private String workDuties;
	private String workTitle;
	private String mailingAddress;
	private String phoneNumber;
	private String fixedTelephone;
	private String mail;
	private String education;
	private String academicDegree;
	private String major;
	private String graduateSchool;
	private String nowMajor;
	private Integer field;
	private String jobResume;
	private String familiarField;
	private String researchProject;
	private String publishedPapers;
	private String publishedMonograph;
	private String scienceTechnology;
	private String onlyProperty;
	private String projectDevelopment;
	private String declarationPath;
	private String professionalPath;
	private String educationPath;
	private String note;
	private Byte isPass;

	public Apply() {
	}

	public Apply(User user, String name, String sex, Date brithday,
			String idCard, String politicalStatus, String nation,
			String workType, String workName, String department,
			String workAddress, String inchPhoto, String workDuties,
			String workTitle, String mailingAddress, String phoneNumber,
			String fixedTelephone, String mail, String education,
			String academicDegree, String major, String graduateSchool,
			String nowMajor, Integer field, String jobResume,
			String familiarField, String researchProject,
			String publishedPapers, String publishedMonograph,
			String scienceTechnology, String onlyProperty,
			String projectDevelopment, String declarationPath,
			String professionalPath, String educationPath, String note,
			Byte isPass) {
		this.user = user;
		this.name = name;
		this.sex = sex;
		this.brithday = brithday;
		this.idCard = idCard;
		this.politicalStatus = politicalStatus;
		this.nation = nation;
		this.workType = workType;
		this.workName = workName;
		this.department = department;
		this.workAddress = workAddress;
		this.inchPhoto = inchPhoto;
		this.workDuties = workDuties;
		this.workTitle = workTitle;
		this.mailingAddress = mailingAddress;
		this.phoneNumber = phoneNumber;
		this.fixedTelephone = fixedTelephone;
		this.mail = mail;
		this.education = education;
		this.academicDegree = academicDegree;
		this.major = major;
		this.graduateSchool = graduateSchool;
		this.nowMajor = nowMajor;
		this.field = field;
		this.jobResume = jobResume;
		this.familiarField = familiarField;
		this.researchProject = researchProject;
		this.publishedPapers = publishedPapers;
		this.publishedMonograph = publishedMonograph;
		this.scienceTechnology = scienceTechnology;
		this.onlyProperty = onlyProperty;
		this.projectDevelopment = projectDevelopment;
		this.declarationPath = declarationPath;
		this.professionalPath = professionalPath;
		this.educationPath = educationPath;
		this.note = note;
		this.isPass = isPass;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "Name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Sex", length = 2)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Brithday", length = 10)
	public Date getBrithday() {
		return this.brithday;
	}

	public void setBrithday(Date brithday) {
		this.brithday = brithday;
	}

	@Column(name = "IdCard", length = 20)
	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	@Column(name = "PoliticalStatus", length = 20)
	public String getPoliticalStatus() {
		return this.politicalStatus;
	}

	public void setPoliticalStatus(String politicalStatus) {
		this.politicalStatus = politicalStatus;
	}

	@Column(name = "Nation", length = 10)
	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	@Column(name = "WorkType", length = 30)
	public String getWorkType() {
		return this.workType;
	}

	public void setWorkType(String workType) {
		this.workType = workType;
	}

	@Column(name = "WorkName", length = 50)
	public String getWorkName() {
		return this.workName;
	}

	public void setWorkName(String workName) {
		this.workName = workName;
	}

	@Column(name = "Department", length = 50)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "WorkAddress", length = 50)
	public String getWorkAddress() {
		return this.workAddress;
	}

	public void setWorkAddress(String workAddress) {
		this.workAddress = workAddress;
	}

	@Column(name = "InchPhoto")
	public String getInchPhoto() {
		return this.inchPhoto;
	}

	public void setInchPhoto(String inchPhoto) {
		this.inchPhoto = inchPhoto;
	}

	@Column(name = "WorkDuties", length = 50)
	public String getWorkDuties() {
		return this.workDuties;
	}

	public void setWorkDuties(String workDuties) {
		this.workDuties = workDuties;
	}

	@Column(name = "WorkTitle", length = 50)
	public String getWorkTitle() {
		return this.workTitle;
	}

	public void setWorkTitle(String workTitle) {
		this.workTitle = workTitle;
	}

	@Column(name = "MailingAddress", length = 50)
	public String getMailingAddress() {
		return this.mailingAddress;
	}

	public void setMailingAddress(String mailingAddress) {
		this.mailingAddress = mailingAddress;
	}

	@Column(name = "PhoneNumber", length = 15)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "FixedTelephone", length = 20)
	public String getFixedTelephone() {
		return this.fixedTelephone;
	}

	public void setFixedTelephone(String fixedTelephone) {
		this.fixedTelephone = fixedTelephone;
	}

	@Column(name = "Mail", length = 50)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "Education", length = 10)
	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	@Column(name = "AcademicDegree", length = 10)
	public String getAcademicDegree() {
		return this.academicDegree;
	}

	public void setAcademicDegree(String academicDegree) {
		this.academicDegree = academicDegree;
	}

	@Column(name = "Major", length = 20)
	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	@Column(name = "GraduateSchool", length = 50)
	public String getGraduateSchool() {
		return this.graduateSchool;
	}

	public void setGraduateSchool(String graduateSchool) {
		this.graduateSchool = graduateSchool;
	}

	@Column(name = "NowMajor", length = 50)
	public String getNowMajor() {
		return this.nowMajor;
	}

	public void setNowMajor(String nowMajor) {
		this.nowMajor = nowMajor;
	}

	@Column(name = "Field")
	public Integer getField() {
		return this.field;
	}

	public void setField(Integer field) {
		this.field = field;
	}

	@Column(name = "JobResume", length = 65535)
	public String getJobResume() {
		return this.jobResume;
	}

	public void setJobResume(String jobResume) {
		this.jobResume = jobResume;
	}

	@Column(name = "FamiliarField", length = 65535)
	public String getFamiliarField() {
		return this.familiarField;
	}

	public void setFamiliarField(String familiarField) {
		this.familiarField = familiarField;
	}

	@Column(name = "ResearchProject", length = 65535)
	public String getResearchProject() {
		return this.researchProject;
	}

	public void setResearchProject(String researchProject) {
		this.researchProject = researchProject;
	}

	@Column(name = "PublishedPapers", length = 65535)
	public String getPublishedPapers() {
		return this.publishedPapers;
	}

	public void setPublishedPapers(String publishedPapers) {
		this.publishedPapers = publishedPapers;
	}

	@Column(name = "PublishedMonograph", length = 65535)
	public String getPublishedMonograph() {
		return this.publishedMonograph;
	}

	public void setPublishedMonograph(String publishedMonograph) {
		this.publishedMonograph = publishedMonograph;
	}

	@Column(name = "ScienceTechnology", length = 65535)
	public String getScienceTechnology() {
		return this.scienceTechnology;
	}

	public void setScienceTechnology(String scienceTechnology) {
		this.scienceTechnology = scienceTechnology;
	}

	@Column(name = "OnlyProperty", length = 65535)
	public String getOnlyProperty() {
		return this.onlyProperty;
	}

	public void setOnlyProperty(String onlyProperty) {
		this.onlyProperty = onlyProperty;
	}

	@Column(name = "ProjectDevelopment", length = 65535)
	public String getProjectDevelopment() {
		return this.projectDevelopment;
	}

	public void setProjectDevelopment(String projectDevelopment) {
		this.projectDevelopment = projectDevelopment;
	}

	@Column(name = "DeclarationPath")
	public String getDeclarationPath() {
		return this.declarationPath;
	}

	public void setDeclarationPath(String declarationPath) {
		this.declarationPath = declarationPath;
	}

	@Column(name = "ProfessionalPath")
	public String getProfessionalPath() {
		return this.professionalPath;
	}

	public void setProfessionalPath(String professionalPath) {
		this.professionalPath = professionalPath;
	}

	@Column(name = "EducationPath")
	public String getEducationPath() {
		return this.educationPath;
	}

	public void setEducationPath(String educationPath) {
		this.educationPath = educationPath;
	}

	@Column(name = "Note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "IsPass")
	public Byte getIsPass() {
		return this.isPass;
	}

	public void setIsPass(Byte isPass) {
		this.isPass = isPass;
	}

}
