package com.jingxin.hibernate.model;

// Generated 2015-12-30 11:13:07 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Setup generated by hbm2java
 */
@Entity
@Table(name = "setup", catalog = "jingxin")
public class Setup implements java.io.Serializable {

	private String name;
	private String value;

	public Setup() {
	}

	public Setup(String name, String value) {
		this.name = name;
		this.value = value;
	}

	@Id
	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
